version: '3.7'
services:
  authentication:
    build: .
    container_name: ms-auth
    restart: always
    volumes:
      - ./dist:/usr/app/dist
    ports:
      - 8090:8090
    depends_on:
      -  database

  database:
    image: mongo
    container_name: mongo-auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro