version: '3.7'

services:

  circletv-ms-authentication:
    build: .
    restart: always
    ports:
      - 8090:8090
    environment:
      MS_AUTHENTICATION_DB_HOSTNAME: root
      MS_AUTHENTICATION_DB_PORT: example

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example