version: '3.7'

services:

  circletv-ms-authentication:
    build: .
    container_name: ms-authentication
    restart: always
    ports:
      - 8090:8090
    environment:
      MS_AUTHENTICATION_DB_HOSTNAME: root
      MS_AUTHENTICATION_DB_PORT: example