version: '3.7'
services:
  circletv-ms-authentication:
    image: toniton/microservices-authentication:latest
    restart: always
    ports:
      - 8090:8090
    env_file:
      - .env
    external_links:
      - mongo
    networks:
      - mongo
networks:
  mongo:
    external: true